export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
	textOperators: [
		{ label: "Is", value: "eq" as const },
		{ label: "Is not", value: "ne" as const },
		{ label: "Contains", value: "iLike" as const },
		{ label: "Does not contain", value: "notILike" as const },
		{ label: "Starts with", value: "startsWith" as const },
		{ label: "Ends with", value: "endsWith" as const },
		{ label: "Is empty", value: "isEmpty" as const },
		{ label: "Is not empty", value: "isNotEmpty" as const },
	],
	numericOperators: [
		{ label: "=", value: "eq" as const },
		{ label: "≠", value: "ne" as const },
		{ label: ">", value: "gt" as const },
		{ label: "<", value: "lt" as const },
		{ label: "≥", value: "gte" as const },
		{ label: "≤", value: "lte" as const },
		{ label: "Is empty", value: "isEmpty" as const },
		{ label: "Is not empty", value: "isNotEmpty" as const },
	],
	dateOperators: [
		{ label: "Is", value: "eq" as const },
		{ label: "Is before", value: "lt" as const },
		{ label: "Is after", value: "gt" as const },
		{ label: "Is on or before", value: "lte" as const },
		{ label: "Is on or after", value: "gte" as const },
		{ label: "Is between", value: "isBetween" as const },
		{ label: "Is relative to today", value: "isRelativeToToday" as const },
		{ label: "Is empty", value: "isEmpty" as const },
		{ label: "Is not empty", value: "isNotEmpty" as const },
	],
	selectOperators: [
		{ label: "Is", value: "eq" as const },
		{ label: "Is not", value: "ne" as const },
		{ label: "Is empty", value: "isEmpty" as const },
		{ label: "Is not empty", value: "isNotEmpty" as const },
	],
	multiSelectOperators: [
		{ label: "Contains", value: "inArray" as const },
		{ label: "Does not contain", value: "notInArray" as const },
		{ label: "Is empty", value: "isEmpty" as const },
		{ label: "Is not empty", value: "isNotEmpty" as const },
	],
	booleanOperators: [
		{ label: "Is", value: "eq" as const },
		{ label: "Is not", value: "ne" as const },
	],
	filesOperators: [
		{ label: "Is not empty", value: "isNotEmpty" as const },
		{ label: "Is empty", value: "isEmpty" as const },
	],
	sortOrders: [
		{ label: "Asc", value: "asc" as const },
		{ label: "Desc", value: "desc" as const },
	],
	filterVariants: [
		"text",
		"number",
		"range",
		"date",
		"dateRange",
		"boolean",
		"select",
		"multiSelect",
		"files",
	] as const,
	operators: [
		"iLike",
		"notILike",
		"eq",
		"ne",
		"inArray",
		"notInArray",
		"isEmpty",
		"isNotEmpty",
		"lt",
		"lte",
		"gt",
		"gte",
		"isBetween",
		"isRelativeToToday",
		"startsWith",
		"endsWith",
	] as const,
	joinOperators: ["and", "or"] as const,
};
