name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup tools
        uses: ./.github/actions/setup-tools

      - name: Run Check (Lint + Format)
        run: bun run check

      - name: Run Type Check
        run: bun run check-types

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup tools
        uses: ./.github/actions/setup-tools

      - name: Build
        run: bun run build

  status:
    needs: [lint, build]
    if: ${{ always() }}
    uses: ./.github/workflows/workflow-check.yml
    with:
      json-needs: ${{ toJSON(needs) }}
      error-message: "One or more of the CI jobs have failed. Please view the jobs for this workflow run for more details."
